name: example
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  day_night_themed_switcher:
    path: ../
flutter:
  uses-material-design: true