name: day_night_themed_switcher
description: "A beautiful day and night switch"
version: 0.0.1
#homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1
  flutter_inset_box_shadow: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: